# Service configurations

services:
  vm:
    - name: "vm-1"
      cpu_cores: 32
      memory_gb: 128
      io_bandwidth_mbps: 1250
      network_bandwidth_mbps: 1250
      cost_per_hour: 1.536

  faas:
    - name: "faas-cluster-1"
      num_instances: 100
      memory_per_instance_gb: 4
      cpu_per_instance: 1.2
      io_per_instance_mbps: 75
      cost_per_gb_second: 0.0000002
      total_cpu: 120
      total_io: 7500

  qaas:
    - name: "qaas-1"
      cost_per_tb: 5.0
      max_concurrent_queries: 30
      scan_speed_tb_per_sec: 0.5
      base_latency: 5.0
