# Service configurations

# Enabled service types (options: vm, faas, qaas)
# Comment out any service type you don't want to use
enabled_services:
  - vm
  - faas
  - qaas

services:
  vm:
    - name: "vm"
      endpoint: "<VM_WORKER_ENDPOINT>"
      cpu_cores: 32
      memory_gb: 128
      io_bandwidth_mbps: 1250
      network_bandwidth_mbps: 1250
      cost_per_hour: 1.536

  faas:
    cost_per_gb_second: 0.0000166667
    memory_sizes_gb: [2, 4, 6, 8, 10]

  qaas:
    - name: "qaas"
      cost_per_tb: 5.0
      max_concurrent_queries: 30
      scan_speed_tb_per_sec: 0.5
      base_latency: 5.0
